name: parse
description: Parse Server Dart SDK.
version: 0.0.1
#homepage: https://www.github.com/lotux
#author: lotux <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  websockets: 0.2.1+1

dev_dependencies:
  test: ^0.12.0
